PYNGUIN_DANGER_AWARE=1 pynguin   --project-path ./flask-cloud-server   --module-name AES_encrypt_module   --output-path ./test                                 
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'UnsupportedDigestmodError' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'VoidPointer_ctypes' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'int' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'RegexFlag' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'NoneType' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'int' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'bool' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'dict' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'RegexFlag' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'int' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'RegexFlag' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'bytes' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'list' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'int' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'bool' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'float' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'bytes' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'int' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'bytes' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'bytes' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'bool' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'int' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: '_EnumDict' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'bytes' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'bytes' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'bytes' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'str' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'bytes' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'dict' object is not callable
Exception ignored in: <function SmartPointer.__del__ at 0x7f0fb0ff5900>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'dict' object is not callable
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 281, in __del__
    self._destructor(self._raw_pointer)
TypeError: 'dict' object is not callable
------ AES-GCM Encryption ------
    self._destructor(self._raw_pointer)
TypeError: 'dict' object is not callable
------ AES-GCM Encryption ------
encryption input         :Your_plain_text
encryption output        :lyDg4jJEZX+CQ6l/Ir+ncidoWILgojzAOkqDkMOz9Ia25tES6kYZsTqR3ez3iXahtoLajDVqxDLx4N8=    
TypeError: 'dict' object is not callable
------ AES-GCM Encryption ------
encryption input         :Your_plain_text
encryption output        :lyDg4jJEZX+CQ6l/Ir+ncidoWILgojzAOkqDkMOz9Ia25tES6kYZsTqR3ez3iXahtoLajDVqxDLx4N8=    
------ AES-GCM Encryption ------
encryption input         :Your_plain_text
encryption output        :lyDg4jJEZX+CQ6l/Ir+ncidoWILgojzAOkqDkMOz9Ia25tES6kYZsTqR3ez3iXahtoLajDVqxDLx4N8=    

encryption input         :Your_plain_text
encryption output        :lyDg4jJEZX+CQ6l/Ir+ncidoWILgojzAOkqDkMOz9Ia25tES6kYZsTqR3ez3iXahtoLajDVqxDLx4N8=    

------ AES-GCM Decryption ------
decryption input         :lyDg4jJEZX+CQ6l/Ir+ncidoWILgojzAOkqDkMOz9Ia25tES6kYZsTqR3ez3iXahtoLajDVqxDLx4N8=    
decryption output        :Your_plain_text

------ AES-GCM Decryption ------
decryption input         :lyDg4jJEZX+CQ6l/Ir+ncidoWILgojzAOkqDkMOz9Ia25tES6kYZsTqR3ez3iXahtoLajDVqxDLx4N8=    
decryption output        :Your_plain_text
------ AES-GCM Decryption ------
decryption input         :lyDg4jJEZX+CQ6l/Ir+ncidoWILgojzAOkqDkMOz9Ia25tES6kYZsTqR3ez3iXahtoLajDVqxDLx4N8=    
decryption output        :Your_plain_text
------ AES-GCM Encryption ------
decryption input         :lyDg4jJEZX+CQ6l/Ir+ncidoWILgojzAOkqDkMOz9Ia25tES6kYZsTqR3ez3iXahtoLajDVqxDLx4N8=    
decryption output        :Your_plain_text
------ AES-GCM Encryption ------
------ AES-GCM Encryption ------
encryption input         :Your_plain_text
encryption input         :Your_plain_text
encryption output        :by6uMmK+RZXvCpPZjYFJ3aExW700z3bH7/DTrVGamwoOFAf5Ja5daF1dyJt2zKMD6sVSZQhcvLlgBpU=    
encryption output        :by6uMmK+RZXvCpPZjYFJ3aExW700z3bH7/DTrVGamwoOFAf5Ja5daF1dyJt2zKMD6sVSZQhcvLlgBpU=    

------ AES-GCM Decryption ------
decryption input         :by6uMmK+RZXvCpPZjYFJ3aExW700z3bH7/DTrVGamwoOFAf5Ja5daF1dyJt2zKMD6sVSZQhcvLlgBpU=    
decryption output        :Your_plain_text